export const GET_USERS = 'GET_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_OPEN_TRANSACTIONS = 'GET_OPEN_TRANSACTIONS';
export const GET_ACTION_REQUIRED = 'GET_ACTION_REQUIRED';
export const SET_LOADING = 'SET_LOADING';
export const GET_CLOSED_TRANSACTIONS = 'GET_CLOSED_TRANSACTIONS'
export const USERS_ERROR = 'USERS_ERROR'
